<template>
  <div class="overflow-hidden">
    <!-- --- Hero Section --- -->
    <section class="relative pt-40 pb-48 lg:pt-52 lg:pb-64 mesh-bg text-white overflow-hidden hero-pattern">
      <div class="max-w-7xl mx-auto px-6 relative z-10 text-center">
        <FadeIn>
          <h1 class="text-5xl md:text-7xl lg:text-[5.5rem] font-light tracking-tight leading-[1.1] mb-8">
            Short URLs,<br />
            <span class="font-medium text-white">Perfect Symmetry.</span>
          </h1>
        </FadeIn>
        <FadeIn :delay="200">
          <p class="text-lg md:text-xl text-white/80 max-w-2xl mx-auto font-light leading-relaxed mb-12">
            Experience the world's first URL shortener that generates beautiful, palindromic links. Organized by design, built for developers, and entirely free.
          </p>
        </FadeIn>
        
        <FadeIn :delay="400">
          <url-input />
          <div class="mt-8 flex items-center justify-center gap-6 text-sm font-medium text-white/70">
            <router-link to="/auth/register" class="hover:text-white transition-colors">Get Started for Free</router-link>
            <span class="w-1 h-1 rounded-full bg-white/30"></span>
            <a href="#api" class="hover:text-white transition-colors flex items-center gap-2">
              <CodeBracketIcon class="w-4 h-4" /> View API Docs
            </a>
          </div>
        </FadeIn>
      </div>
    </section>

    <!-- --- The Palindot Edge --- -->
    <section id="features" class="relative -mt-32 z-20 max-w-7xl mx-auto px-6 mb-32">
      <FadeIn>
        <div class="bg-white/80 backdrop-blur-xl rounded-[2.5rem] p-10 md:p-16 smooth-shadow border border-white/50">
          <div class="flex flex-col lg:flex-row gap-16">
            
            <div class="lg:w-1/3">
              <p class="text-sm font-bold tracking-widest uppercase text-[#62859B] mb-4">Core Features</p>
              <h2 class="text-4xl md:text-5xl font-light leading-tight text-gray-900 mb-6">
                The Palindot Edge
              </h2>
              <div class="w-20 h-0.5 bg-gray-200 mb-8"></div>
              <div class="bg-white rounded-3xl p-8 border border-gray-100 shadow-sm">
                <div class="w-12 h-12 bg-[#F2F4F6] rounded-2xl flex items-center justify-center mb-6 text-[#62859B]">
                  <Square3Stack3DIcon class="w-6 h-6" />
                </div>
                <h3 class="text-2xl font-medium mb-4 text-gray-900">Palindromic Precision</h3>
                <p class="text-gray-500 font-light leading-relaxed">
                  Every link generated by Palindot is a palindrome. It's not just a short URL; it's a balanced piece of digital identity.
                </p>
              </div>
            </div>

            <div class="lg:w-2/3 grid grid-cols-1 md:grid-cols-2 gap-6">
              <div class="bg-gradient-to-br from-[#1A1A1A] to-[#2D2D2D] text-white rounded-3xl p-10 flex flex-col justify-between group h-full hover:-translate-y-2 transition-transform duration-500 shadow-lg">
                <div>
                  <div class="w-12 h-12 bg-white/10 rounded-2xl flex items-center justify-center mb-8">
                    <CircleStackIcon class="w-6 h-6 text-white" />
                  </div>
                  <h3 class="text-2xl font-medium mb-4">Organize with Subsets</h3>
                  <p class="text-white/60 font-light leading-relaxed">
                    Stop losing track of your links. Group your URLs into custom Subsets for different projects, campaigns, or clients.
                  </p>
                </div>
              </div>

              <div class="bg-gradient-to-br from-[#DFCCC0] to-[#D5C4B5] rounded-3xl p-10 flex flex-col justify-between group h-full hover:-translate-y-2 transition-transform duration-500 shadow-lg">
                <div>
                  <div class="w-12 h-12 bg-white/40 backdrop-blur-md rounded-2xl flex items-center justify-center mb-8 shadow-sm">
                    <CodeBracketIcon class="w-6 h-6 text-gray-900" />
                  </div>
                  <h3 class="text-2xl font-medium mb-4 text-gray-900">Built for Integration</h3>
                  <p class="text-gray-800/80 font-light leading-relaxed">
                    Full OpenAPI/Swagger support allows you to integrate Palindot's symmetrical link generation directly into your own applications.
                  </p>
                </div>
              </div>
            </div>

          </div>
        </div>
      </FadeIn>
    </section>

    <!-- --- How It Works --- -->
    <section class="py-24 bg-[#F2F4F6]">
      <div class="max-w-7xl mx-auto px-6">
        <FadeIn>
          <div class="text-center max-w-2xl mx-auto mb-20">
            <h2 class="text-4xl md:text-5xl font-light text-gray-900 mb-6">Simple & Fast</h2>
            <p class="text-gray-500 font-light text-lg">Three steps to achieving perfect symmetry for your links.</p>
          </div>
        </FadeIn>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-8 relative">
          <div class="hidden md:block absolute top-1/2 left-10 right-10 h-px bg-gray-200 -z-10"></div>
          
          <FadeIn v-for="(step, idx) in steps" :key="idx" :delay="idx * 200">
            <div class="bg-white rounded-[2rem] p-10 text-center smooth-shadow border border-white/60 relative hover:-translate-y-1 transition-transform h-full">
              <div class="w-16 h-16 mx-auto bg-[#F2F4F6] rounded-full flex items-center justify-center text-[#62859B] mb-6">
                <component :is="step.icon" class="w-6 h-6" />
              </div>
              <h3 class="text-xl font-medium mb-4 text-gray-900">{{ step.title }}</h3>
              <p class="text-gray-500 font-light">{{ step.desc }}</p>
            </div>
          </FadeIn>
        </div>
      </div>
    </section>

    <!-- --- Dashboard Experience --- -->
    <section id="dashboard" class="py-32 bg-white">
      <div class="max-w-7xl mx-auto px-6">
        <div class="bg-[#DFCCC0] rounded-[3rem] p-8 lg:p-16 smooth-shadow">
          <div class="flex flex-col lg:flex-row items-center gap-16 lg:gap-20">
            <div class="lg:w-1/2">
              <FadeIn>
                <h2 class="text-4xl md:text-5xl font-light text-gray-900 mb-6 leading-tight">
                  Your Links,<br />Reimagined.
                </h2>
                <p class="text-lg text-gray-900/70 font-light leading-relaxed mb-10">
                  Our intuitive dashboard gives you a bird's-eye view of your entire link library. Filter by subsets, edit destinations on the fly, and export your data whenever you need it.
                </p>
                <ul class="space-y-4">
                  <li v-for="(item, i) in dashboardFeatures" :key="i" class="flex items-center gap-3 text-gray-900 font-medium">
                    <div class="w-6 h-6 rounded-full bg-white/40 flex items-center justify-center text-[#1A1A1A]">
                      <ChartBarIcon class="w-3 h-3" />
                    </div>
                    {{ item }}
                  </li>
                </ul>
              </FadeIn>
            </div>

            <div class="lg:w-1/2 w-full">
              <FadeIn :delay="300">
                <div class="bg-white/40 backdrop-blur-sm rounded-[2rem] p-4 sm:p-6 shadow-2xl border border-white/50">
                  <div class="bg-white rounded-2xl overflow-hidden border border-gray-100 flex flex-col h-[400px]">
                    <!-- Mock Header -->
                    <div class="h-14 border-b border-gray-100 flex items-center px-6 justify-between bg-gray-50/50">
                      <div class="flex gap-2">
                        <div class="w-3 h-3 rounded-full bg-red-400"></div>
                        <div class="w-3 h-3 rounded-full bg-amber-400"></div>
                        <div class="w-3 h-3 rounded-full bg-green-400"></div>
                      </div>
                      <div class="text-xs font-semibold text-gray-500 uppercase tracking-widest flex items-center gap-2">
                        <ChartBarIcon class="w-3 h-3 text-[#62859B]" />
                        Live Dashboard
                      </div>
                    </div>
                    <!-- Mock Body -->
                    <div class="flex flex-1 overflow-hidden">
                      <!-- Mock Sidebar -->
                      <div class="w-1/3 border-r border-gray-100 p-4 space-y-1 bg-gray-50/50">
                        <div class="px-3 py-2 text-xs font-bold text-gray-400 uppercase tracking-wider mb-2 text-[10px]">Subsets</div>
                        <div v-for="(subset, idx) in ['Marketing', 'Personal', 'Clients']" :key="idx" 
                             :class="['px-3 py-2.5 rounded-xl text-[12px] font-medium flex items-center justify-between cursor-pointer transition-colors', idx === 0 ? 'bg-white shadow-sm border border-gray-100 text-[#62859B]' : 'text-gray-500 hover:bg-gray-100/50']">
                          {{ subset }}
                          <span :class="['text-[10px]', idx === 0 ? 'text-[#62859B]' : 'text-gray-400']">{{ 12 - idx * 3 }}</span>
                        </div>
                        <div class="mt-4 px-3 py-2 text-[12px] text-gray-400 font-medium flex items-center gap-2 cursor-pointer hover:text-gray-600 transition-colors">
                          <span class="text-lg leading-none">+</span> New
                        </div>
                      </div>
                      <!-- Mock Content -->
                      <div class="w-2/3 p-6 bg-white overflow-y-auto">
                        <div class="flex justify-between items-center mb-6">
                          <div>
                            <h3 class="text-sm font-semibold text-gray-900">Marketing</h3>
                            <p class="text-[10px] text-gray-400">Updated just now</p>
                          </div>
                          <button class="bg-[#1A1A1A] text-white text-[10px] px-3 py-1.5 rounded-full font-medium hover:bg-black transition-colors flex items-center gap-1">
                             <LinkIcon class="w-3 h-3" /> Create
                          </button>
                        </div>
                        <div class="space-y-3">
                          <div v-for="(link, i) in mockLinks" :key="i" class="group p-3 border border-gray-100 rounded-xl hover:shadow-md hover:border-gray-200 transition-all cursor-pointer">
                            <div class="flex items-center justify-between mb-1">
                              <div class="flex items-center gap-2 truncate">
                                <div :class="['w-1.5 h-1.5 rounded-full', link.status]"></div>
                                <span class="font-semibold text-gray-900 text-[11px] truncate">{{ link.alias }}</span>
                              </div>
                              <span class="text-[9px] font-medium text-gray-500 bg-gray-50 px-1.5 py-0.5 rounded-md whitespace-nowrap">{{ link.clicks }} clks</span>
                            </div>
                            <div class="flex items-center gap-1 text-[9px] text-gray-400 ml-3.5 truncate">
                              <ArrowRightIcon class="w-2 h-2" /> {{ link.dest }}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </FadeIn>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- --- Technical Excellence --- -->
    <section id="api" class="py-24 bg-white text-gray-900 border-t border-gray-100">
      <div class="max-w-7xl mx-auto px-6">
        <FadeIn>
          <div class="text-center mb-20">
            <h2 class="text-4xl md:text-5xl font-light mb-6 text-gray-900">Robust. Secure. Open.</h2>
            <p class="text-gray-500 font-light text-lg max-w-2xl mx-auto">Engineered for performance and seamless integration.</p>
          </div>
        </FadeIn>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
          <FadeIn v-for="(feature, idx) in techFeatures" :key="idx" :delay="idx * 100">
            <div class="bg-[#F2F4F6] border border-gray-100 rounded-3xl p-10 hover:shadow-lg transition-all hover:-translate-y-1 h-full">
              <component :is="feature.icon" class="text-[#62859B] mb-6 w-8 h-8" />
              <h3 class="text-xl font-medium mb-4 text-gray-900">{{ feature.title }}</h3>
              <p class="text-gray-500 font-light leading-relaxed">
                {{ feature.desc }}
              </p>
            </div>
          </FadeIn>
        </div>
      </div>
    </section>

    <!-- --- Final Call to Action --- -->
    <section class="py-32 bg-[#F2F4F6]">
      <div class="max-w-5xl mx-auto px-6">
        <FadeIn>
          <div class="bg-gradient-to-br from-[#DFCCC0]/40 to-[#FFFFFF] rounded-[3rem] p-16 md:p-24 text-center border border-white smooth-shadow">
            <h2 class="text-4xl md:text-6xl font-light text-gray-900 mb-8">Ready to balance your links?</h2>
            <p class="text-xl text-gray-500 font-light mb-12 max-w-2xl mx-auto">
              Join Palindot today and start creating symmetrical, organized URLs in seconds.
            </p>
            <router-link to="/auth/register" class="inline-block bg-[#1A1A1A] text-white px-10 py-5 rounded-full text-lg font-medium hover:bg-black transition-all transform hover:scale-105 shadow-xl shadow-black/10">
              Create Your Account
            </router-link>
          </div>
        </FadeIn>
      </div>
    </section>
  </div>
</template>

<script setup>
import { 
  LinkIcon, 
  ArrowRightIcon, 
  CodeBracketIcon, 
  Square3Stack3DIcon, 
  ShieldCheckIcon, 
  FunnelIcon, 
  BoltIcon, 
  ChartBarIcon,
  CircleStackIcon
} from '@heroicons/vue/24/outline';
import urlInput from '../../components/url-input.vue';
import FadeIn from '../../components/FadeIn.vue';

const steps = [
  { title: "Paste your link", desc: "Enter any long URL into the generator.", icon: LinkIcon },
  { title: "Instant Symmetry", desc: "Our algorithm generates a unique, palindromic alias.", icon: BoltIcon },
  { title: "Manage & Track", desc: "Save links to subsets and monitor their performance.", icon: ChartBarIcon }
];

const dashboardFeatures = [
  'Filter by subsets',
  'Edit destinations on the fly',
  'Export your data'
];

const mockLinks = [
  { alias: 'p.dot/racecar', clicks: '2.4k', status: 'bg-green-500', dest: 'example.com/summer-promo' },
  { alias: 'p.dot/kayak', clicks: '850', status: 'bg-amber-500', dest: 'example.com/about-us' },
  { alias: 'p.dot/level', clicks: '1.2k', status: 'bg-green-500', dest: 'example.com/app-download' }
];

const techFeatures = [
  { 
    title: "Sanctum Auth", 
    desc: "Industry-standard security for your account and API access, ensuring your data remains protected.", 
    icon: ShieldCheckIcon 
  },
  { 
    title: "RESTful API", 
    desc: "Clean, predictable API endpoints for all operations, making integration a breeze for developers.", 
    icon: CodeBracketIcon 
  },
  { 
    title: "Advanced Filters", 
    desc: "Advanced filtering for both URLs and Subsets to find exactly what you need instantly.", 
    icon: FunnelIcon 
  }
];
</script>